<?php
	// Liste de véhicules
	$arrayShips = [

			// Structure d'un élément
			[
				'name' => 'Executor',
				'manufacturer' => 'Kuat Drive Yards, Fondor Shipyards',
				'class' => 'Star dreadnought',
				'cost_in_credits' => 1143350000,
				'length' => 19000,
				'max_atmosphering_speed' => null
			],

			// Les autres éléments
			['name' => 'Sentinel-class landing craft', 'manufacturer' => 'Sienar Fleet Systems, Cyngus Spaceworks', 'class' => 'landing craft', 'cost_in_credits' => 240000, 'length' => 38, 'max_atmosphering_speed' => 1000,],
			['name' => 'Death Star', 'manufacturer' => 'Imperial Department of Military Research, Sienar Fleet Systems', 'class' => 'Deep Space Mobile Battlestation', 'cost_in_credits' => 1000000000000, 'length' => 120000, 'max_atmosphering_speed' => null,],
			['name' => 'Millennium Falcon', 'manufacturer' => 'Corellian Engineering Corporation', 'class' => 'Light freighter', 'cost_in_credits' => 100000, 'length' => 34.37, 'max_atmosphering_speed' => 1050,],
			['name' => 'Y-wing', 'manufacturer' => 'Koensayr Manufacturing', 'class' => 'assault starfighter', 'cost_in_credits' => 134999, 'length' => 14, 'max_atmosphering_speed' => 1000],
			['name' => 'X-wing', 'manufacturer' => 'Incom Corporation', 'class' => 'Starfighter', 'cost_in_credits' => 149999, 'length' => 12.5, 'max_atmosphering_speed' => 1050,],
			['name' => 'TIE Advanced x1', 'manufacturer' => 'Sienar Fleet Systems', 'class' => 'Starfighter', 'cost_in_credits' => null, 'length' => 9.2, 'max_atmosphering_speed' => 1200,],
			['name' => 'Slave 1', 'manufacturer' => 'Kuat Systems Engineering', 'class' => 'Patrol craft', 'cost_in_credits' => null, 'length' => 21.5, 'max_atmosphering_speed' => 1000,],
			['name' => 'Imperial shuttle', 'manufacturer' => 'Sienar Fleet Systems', 'class' => 'Armed government transport', 'cost_in_credits' => 240000, 'length' => 20, 'max_atmosphering_speed' => 850,],
			['name' => 'EF76 Nebulon-B escort frigate', 'manufacturer' => 'Kuat Drive Yards', 'class' => 'Escort ship', 'cost_in_credits' => 8500000, 'length' => 300, 'max_atmosphering_speed' => 800,],
			['name' => 'Calamari Cruiser', 'manufacturer' => 'Mon Calamari shipyards', 'class' => 'Star Cruiser', 'cost_in_credits' => 104000000, 'length' => 1200, 'max_atmosphering_speed' => null,],
			['name' => 'A-wing', 'manufacturer' => 'Alliance Underground Engineering, Incom Corporation', 'class' => 'Starfighter', 'cost_in_credits' => 175000, 'length' => 9.6, 'max_atmosphering_speed' => 1300,],
			['name' => 'B-wing', 'manufacturer' => 'Slayn & Korpil', 'class' => 'Assault Starfighter', 'cost_in_credits' => 220000, 'length' => 16.9, 'max_atmosphering_speed' => 950,],
			['name' => 'Republic Cruiser', 'manufacturer' => 'Corellian Engineering Corporation', 'class' => 'Space cruiser', 'cost_in_credits' => null, 'length' => 115, 'max_atmosphering_speed' => 900,],
			['name' => 'Naboo fighter', 'manufacturer' => 'Theed Palace Space Vessel Engineering Corps', 'class' => 'Starfighter', 'cost_in_credits' => 200000, 'length' => 11, 'max_atmosphering_speed' => 1100,],
			['name' => 'Naboo Royal Starship', 'manufacturer' => 'Theed Palace Space Vessel Engineering Corps, Nubia Star Drives', 'class' => 'yacht', 'cost_in_credits' => null, 'length' => 76, 'max_atmosphering_speed' => 920,],
			['name' => 'Scimitar', 'manufacturer' => 'Republic Sienar Systems', 'class' => 'Space Transport', 'cost_in_credits' => 55000000, 'length' => 26.5, 'max_atmosphering_speed' => 1180,],
			['name' => 'J-type diplomatic barge', 'manufacturer' => 'Theed Palace Space Vessel Engineering Corps, Nubia Star Drives', 'class' => 'Diplomatic barge', 'cost_in_credits' => 2000000, 'length' => 39, 'max_atmosphering_speed' => 2000,],
			['name' => 'AA-9 Coruscant freighter', 'manufacturer' => 'Botajef Shipyards', 'class' => 'freighter', 'cost_in_credits' => null, 'length' => 390, 'max_atmosphering_speed' => null,],
			['name' => 'Jedi starfighter', 'manufacturer' => 'Kuat Systems Engineering', 'class' => 'Starfighter', 'cost_in_credits' => 180000, 'length' => 8, 'max_atmosphering_speed' => 1150,],
			['name' => 'H-type Nubian yacht', 'manufacturer' => 'Theed Palace Space Vessel Engineering Corps', 'class' => 'yacht', 'cost_in_credits' => null, 'length' => 47.9, 'max_atmosphering_speed' => 8000,],
			['name' => 'Star Destroyer', 'manufacturer' => 'Kuat Drive Yards', 'class' => 'Star Destroyer', 'cost_in_credits' => 150000000, 'length' => 1,600, 'max_atmosphering_speed' => 975,],
			['name' => 'Trade Federation cruiser', 'manufacturer' => 'Rendili StarDrive, Free Dac Volunteers Engineering corps.', 'class' => 'capital ship', 'cost_in_credits' => 125000000, 'length' => 1088, 'max_atmosphering_speed' => 1050,],
			['name' => 'Theta-class T-2c shuttle', 'manufacturer' => 'Cygnus Spaceworks', 'class' => 'transport', 'cost_in_credits' => 1000000, 'length' => 18.5, 'max_atmosphering_speed' => 2000,],
			['name' => 'T-70 X-wing fighter', 'manufacturer' => 'Incom', 'class' => 'fighter', 'cost_in_credits' => null, 'length' => null, 'max_atmosphering_speed' => null,],
			['name' => 'Rebel transport', 'manufacturer' => 'Gallofree Yards, Inc.', 'class' => 'Medium transport', 'cost_in_credits' => null, 'length' => 90, 'max_atmosphering_speed' => 650,],
			['name' => 'Droid control ship', 'manufacturer' => 'Hoersch-Kessel Drive, Inc.', 'class' => 'Droid control ship', 'cost_in_credits' => null, 'length' => 3170, 'max_atmosphering_speed' => null,],
			['name' => 'Republic Assault ship', 'manufacturer' => 'Rothana Heavy Engineering', 'class' => 'assault ship', 'cost_in_credits' => null, 'length' => 752, 'max_atmosphering_speed' => null,],
			['name' => 'Solar Sailer', 'manufacturer' => 'Huppla Pasa Tisc Shipwrights Collective', 'class' => 'yacht', 'cost_in_credits' => 35700, 'length' => 15.2, 'max_atmosphering_speed' => 1600,],
			['name' => 'Republic attack cruiser', 'manufacturer' => 'Kuat Drive Yards, Allanteen Six shipyards', 'class' => 'star destroyer', 'cost_in_credits' => 59000000, 'length' => 1137, 'max_atmosphering_speed' => 975,],
			['name' => 'Sand Crawler', 'manufacturer' => 'Corellia Mining Corporation', 'class' => 'wheeled', 'cost_in_credits' => 150000, 'length' => 36.8, 'max_atmosphering_speed' => 30,],
			['name' => 'T-16 skyhopper', 'manufacturer' => 'Incom Corporation', 'class' => 'repulsorcraft', 'cost_in_credits' => 14500, 'length' => 10.4, 'max_atmosphering_speed' => 1200,],
			['name' => 'X-34 landspeeder', 'manufacturer' => 'SoroSuub Corporation', 'class' => 'repulsorcraft', 'cost_in_credits' => 10550, 'length' => 3.4, 'max_atmosphering_speed' => 250,],
			['name' => 'TIE/LN starfighter', 'manufacturer' => 'Sienar Fleet Systems', 'class' => 'starfighter', 'cost_in_credits' => null, 'length' => 6.4, 'max_atmosphering_speed' => 1200,],
			['name' => 'Snowspeeder', 'manufacturer' => 'Incom corporation', 'class' => 'airspeeder', 'cost_in_credits' => null, 'length' => 4.5, 'max_atmosphering_speed' => 650,],
			['name' => 'TIE bomber', 'manufacturer' => 'Sienar Fleet Systems', 'class' => 'space/planetary bomber', 'cost_in_credits' => null, 'length' => 7.8, 'max_atmosphering_speed' => 850,],
			['name' => 'AT-AT', 'manufacturer' => 'Kuat Drive Yards, Imperial Department of Military Research', 'class' => 'assault walker', 'cost_in_credits' => null, 'length' => 20, 'max_atmosphering_speed' => 60,],
			['name' => 'AT-ST', 'manufacturer' => 'Kuat Drive Yards, Imperial Department of Military Research', 'class' => 'walker', 'cost_in_credits' => null, 'length' => 2, 'max_atmosphering_speed' => 90,],
			['name' => 'Storm IV Twin-Pod cloud car', 'manufacturer' => 'Bespin Motors', 'class' => 'repulsorcraft', 'cost_in_credits' => 75000, 'length' => 7, 'max_atmosphering_speed' => 1500,],
			['name' => 'Sail barge', 'manufacturer' => 'Ubrikkian Industries Custom Vehicle Division', 'class' => 'sail barge', 'cost_in_credits' => 285000, 'length' => 30, 'max_atmosphering_speed' => 100,],
			['name' => 'Bantha-II cargo skiff', 'manufacturer' => 'Ubrikkian Industries', 'class' => 'repulsorcraft cargo skiff', 'cost_in_credits' => 8000, 'length' => 9.5, 'max_atmosphering_speed' => 250,],
			['name' => 'TIE/IN interceptor', 'manufacturer' => 'Sienar Fleet Systems', 'class' => 'starfighter', 'cost_in_credits' => null, 'length' => 9.6, 'max_atmosphering_speed' => 1250,],
			['name' => 'Imperial Speeder Bike', 'manufacturer' => 'Aratech Repulsor Company', 'class' => 'speeder', 'cost_in_credits' => 8000, 'length' => 3, 'max_atmosphering_speed' => 360,],
			['name' => 'Vulture Droid', 'manufacturer' => 'Haor Chall Engineering, Baktoid Armor Workshop', 'class' => 'starfighter', 'cost_in_credits' => null, 'length' => 3.5, 'max_atmosphering_speed' => 1200,],
			['name' => 'Multi-Troop Transport', 'manufacturer' => 'Baktoid Armor Workshop', 'class' => 'repulsorcraft', 'cost_in_credits' => 138000, 'length' => 31, 'max_atmosphering_speed' => 35,],
			['name' => 'Armored Assault Tank', 'manufacturer' => 'Baktoid Armor Workshop', 'class' => 'repulsorcraft', 'cost_in_credits' => null, 'length' => 9.75, 'max_atmosphering_speed' => 55,],
			['name' => 'Single Trooper Aerial Platform', 'manufacturer' => 'Baktoid Armor Workshop', 'class' => 'repulsorcraft', 'cost_in_credits' => 2500, 'length' => 2, 'max_atmosphering_speed' => 400,],
			['name' => 'C-9979 landing craft', 'manufacturer' => 'Haor Chall Engineering', 'class' => 'landing craft', 'cost_in_credits' => 200000, 'length' => 210, 'max_atmosphering_speed' => 587,],
			['name' => 'Tribubble bongo', 'manufacturer' => 'Otoh Gunga Bongameken Cooperative', 'class' => 'submarine', 'cost_in_credits' => null, 'length' => 15, 'max_atmosphering_speed' => 85,],
			['name' => 'Sith speeder', 'manufacturer' => 'Razalon', 'class' => 'speeder', 'cost_in_credits' => 4000, 'length' => 1.5, 'max_atmosphering_speed' => 180,],
			['name' => 'Zephyr-G swoop bike', 'manufacturer' => 'Mobquet Swoops and Speeders', 'class' => 'repulsorcraft', 'cost_in_credits' => 5750, 'length' => 3.68, 'max_atmosphering_speed' => 350,],
			['name' => 'Koro-2 Exodrive airspeeder', 'manufacturer' => 'Desler Gizh Outworld Mobility Corporation', 'class' => 'airspeeder', 'cost_in_credits' => null, 'length' => 6.6, 'max_atmosphering_speed' => 800,],
			['name' => 'XJ-6 airspeeder', 'manufacturer' => 'Narglatch AirTech prefabricated kit', 'class' => 'airspeeder', 'cost_in_credits' => null, 'length' => 6.23, 'max_atmosphering_speed' => 720,],
			['name' => 'LAAT/i', 'manufacturer' => 'Rothana Heavy Engineering', 'class' => 'gunship', 'cost_in_credits' => null, 'length' => 17.4, 'max_atmosphering_speed' => 620,],
			['name' => 'LAAT/c', 'manufacturer' => 'Rothana Heavy Engineering', 'class' => 'gunship', 'cost_in_credits' => null, 'length' => 28.82, 'max_atmosphering_speed' => 620,],
			['name' => 'Tsmeu-6 personal wheel bike', 'manufacturer' => 'Z-Gomot Ternbuell Guppat Corporation', 'class' => 'wheeled walker', 'cost_in_credits' => 15000, 'length' => 3.5, 'max_atmosphering_speed' => 330,],
			['name' => 'Emergency Firespeeder', 'manufacturer' => 'unknown', 'class' => 'fire suppression ship', 'cost_in_credits' => null, 'length' => null, 'max_atmosphering_speed' => null,],
			['name' => 'Droid tri-fighter', 'manufacturer' => 'Colla Designs, Phlac-Arphocc Automata Industries', 'class' => 'droid starfighter', 'cost_in_credits' => 20000, 'length' => 5.4, 'max_atmosphering_speed' => 1180,],
			['name' => 'Oevvaor jet catamaran', 'manufacturer' => 'Appazanna Engineering Works', 'class' => 'airspeeder', 'cost_in_credits' => 12125, 'length' => 15.1, 'max_atmosphering_speed' => 420,],
			['name' => 'Raddaugh Gnasp fluttercraft', 'manufacturer' => 'Appazanna Engineering Works', 'class' => 'air speeder', 'cost_in_credits' => 14750, 'length' => 7, 'max_atmosphering_speed' => 310,],
		];


		// Liste d'espèces
		$arraySpecies = [

			// Structure d'un élément
			[
				'name' => 'Hutt', 
				'classification' => 'gastropod', 
				'language' => 'Huttese', 
				'average_lifespan' => 1000
			],

			// Les autres éléments
			['name' => 'Yoda\'s species', 'classification' => 'mammal', 'language' => 'Galactic basic', 'average_lifespan' => 900],
			['name' => 'Trandoshan', 'classification' => 'reptile', 'language' => 'Dosh', 'average_lifespan' => null],
			['name' => 'Mon Calamari', 'classification' => 'amphibian', 'language' => 'Mon Calamarian', 'average_lifespan' => null],
			['name' => 'Ewok', 'classification' => 'mammal', 'language' => 'Ewokese', 'average_lifespan' => null],
			['name' => 'Sullustan', 'classification' => 'mammal', 'language' => 'Sullutese', 'average_lifespan' => null],
			['name' => 'Neimodian', 'classification' => 'unknown', 'language' => 'Neimoidia', 'average_lifespan' => null],
			['name' => 'Gungan', 'classification' => 'amphibian', 'language' => 'Gungan basic', 'average_lifespan' => null],
			['name' => 'Toydarian', 'classification' => 'mammal', 'language' => 'Toydarian', 'average_lifespan' => 91],
			['name' => 'Dug', 'classification' => 'mammal', 'language' => 'Dugese', 'average_lifespan' => null],
			['name' => 'Twi\'lek', 'classification' => 'mammals', 'language' => 'Twi\'leki', 'average_lifespan' => null],
			['name' => 'Aleena', 'classification' => 'reptile', 'language' => 'Aleena', 'average_lifespan' => 79],
			['name' => 'Vulptereen', 'classification' => 'unknown', 'language' => 'vulpterish', 'average_lifespan' => null],
			['name' => 'Xexto', 'classification' => 'unknown', 'language' => 'Xextese', 'average_lifespan' => null],
			['name' => 'Toong', 'classification' => 'unknown', 'language' => 'Tundan', 'average_lifespan' => null],
			['name' => 'Cerean', 'classification' => 'mammal', 'language' => 'Cerean', 'average_lifespan' => null],
			['name' => 'Nautolan', 'classification' => 'amphibian', 'language' => 'Nautila', 'average_lifespan' => 70],
			['name' => 'Zabrak', 'classification' => 'mammal', 'language' => 'Zabraki', 'average_lifespan' => null],
			['name' => 'Tholothian', 'classification' => 'mammal', 'language' => 'unknown', 'average_lifespan' => null],
			['name' => 'Iktotchi', 'classification' => 'unknown', 'language' => 'Iktotchese', 'average_lifespan' => null],
			['name' => 'Quermian', 'classification' => 'mammal', 'language' => 'Quermian', 'average_lifespan' => 86],
			['name' => 'Kel Dor', 'classification' => 'unknown', 'language' => 'Kel Dor', 'average_lifespan' => 70],
			['name' => 'Chagrian', 'classification' => 'amphibian', 'language' => 'Chagria', 'average_lifespan' => null],
			['name' => 'Geonosian', 'classification' => 'insectoid', 'language' => 'Geonosian', 'average_lifespan' => null],
			['name' => 'Mirialan', 'classification' => 'mammal', 'language' => 'Mirialan', 'average_lifespan' => null],
			['name' => 'Clawdite', 'classification' => 'reptilian', 'language' => 'Clawdite', 'average_lifespan' => 70],
			['name' => 'Besalisk', 'classification' => 'amphibian', 'language' => 'besalisk', 'average_lifespan' => 75],
			['name' => 'Kaminoan', 'classification' => 'amphibian', 'language' => 'Kaminoan', 'average_lifespan' => 80],
			['name' => 'Skakoan', 'classification' => 'mammal', 'language' => 'Skakoan', 'average_lifespan' => null],
			['name' => 'Muun', 'classification' => 'mammal', 'language' => 'Muun', 'average_lifespan' => 100],
		];

		// Liste de personnage
		$arrayPeople = [

			// Structure d'un élément
			[
				'name' => 'Luke Skywalker', 
				'height' => 172, 
				'mass' => 77, 
				'gender' => 'male', 
				'hair_color' => 'yellow', 
				'skin_color' => '#FFECD3', 
				'eye_color' => 'blue'
			],

			// Les autres éléments
			['name' => 'C-3PO', 'height' => 167, 'mass' => 75, 'gender' => 'robot', 'hair_color' => 'unknown', 'skin_color' => 'gold', 'eye_color' => 'yellow'],
			['name' => 'R2-D2', 'height' => 96, 'mass' => 32, 'gender' => 'robot', 'hair_color' => 'unknown', 'skin_color' => 'white, blue', 'eye_color' => 'red'],
			['name' => 'Darth Vader', 'height' => 202, 'mass' => 136, 'gender' => 'male', 'hair_color' => 'black', 'skin_color' => 'black', 'eye_color' => '#444'],
			['name' => 'Leia Organa', 'height' => 150, 'mass' => 49, 'gender' => 'female', 'hair_color' => 'brown', 'skin_color' => '#fff7ed', 'eye_color' => 'brown'],
			['name' => 'Owen Lars', 'height' => 178, 'mass' => 120, 'gender' => 'male', 'hair_color' => 'brown, grey', 'skin_color' => '#fff7ed', 'eye_color' => 'blue'],
			['name' => 'Beru Whitesun lars', 'height' => 165, 'mass' => 75, 'gender' => 'female', 'hair_color' => 'brown', 'skin_color' => '#fff7ed', 'eye_color' => 'blue'],
			['name' => 'R5-D4', 'height' => 97, 'mass' => 32, 'gender' => 'robot', 'hair_color' => 'unknown', 'skin_color' => 'white, red', 'eye_color' => 'red'],
			['name' => 'Biggs Darklighter', 'height' => 183, 'mass' => 84, 'gender' => 'male', 'hair_color' => 'black', 'skin_color' => '#fff7ed', 'eye_color' => 'brown'],
			['name' => 'Obi-Wan Kenobi', 'height' => 182, 'mass' => 77, 'gender' => 'male', 'hair_color' => 'auburn, white', 'skin_color' => '#FFECD3', 'eye_color' => 'blue-gray'],
			['name' => 'Anakin Skywalker', 'height' => 188, 'mass' => 84, 'gender' => 'male', 'hair_color' => 'yellow', 'skin_color' => '#FFECD3', 'eye_color' => 'blue'],
			['name' => 'Wilhuff Tarkin', 'height' => 180, 'mass' => 79, 'gender' => 'male', 'hair_color' => 'auburn, grey', 'skin_color' => '#FFECD3', 'eye_color' => 'blue'],
			['name' => 'Chewbacca', 'height' => 228, 'mass' => 112, 'gender' => 'male', 'hair_color' => 'brown', 'skin_color' => 'unknown', 'eye_color' => 'blue'],
			['name' => 'Han Solo', 'height' => 180, 'mass' => 80, 'gender' => 'male', 'hair_color' => 'brown', 'skin_color' => '#FFECD3', 'eye_color' => 'brown'],
			['name' => 'Greedo', 'height' => 173, 'mass' => 74, 'gender' => 'male', 'hair_color' => 'unknown', 'skin_color' => 'green', 'eye_color' => 'black'],
			['name' => 'Jabba Desilijic Tiure', 'height' => 175, 'mass' => 1,358, 'gender' => 'hermaphrodite', 'hair_color' => 'unknown', 'skin_color' => 'green-tan, brown', 'eye_color' => 'orange'],
			['name' => 'Wedge Antilles', 'height' => 170, 'mass' => 77, 'gender' => 'male', 'hair_color' => 'brown', 'skin_color' => '#FFECD3', 'eye_color' => 'hazel'],
			['name' => 'Jek Tono Porkins', 'height' => 180, 'mass' => 110, 'gender' => 'male', 'hair_color' => 'brown', 'skin_color' => '#FFECD3', 'eye_color' => 'blue'],
			['name' => 'Yoda', 'height' => 66, 'mass' => 17, 'gender' => 'male', 'hair_color' => 'white', 'skin_color' => 'green', 'eye_color' => 'brown'],
			['name' => 'Palpatine', 'height' => 170, 'mass' => 75, 'gender' => 'male', 'hair_color' => 'grey', 'skin_color' => 'pale', 'eye_color' => 'yellow'],
			['name' => 'Boba Fett', 'height' => 183, 'mass' => 78.2, 'gender' => 'male', 'hair_color' => 'black', 'skin_color' => '#FFECD3', 'eye_color' => 'brown'],
			['name' => 'IG-88', 'height' => 200, 'mass' => 140, 'gender' => 'robot', 'hair_color' => 'none', 'skin_color' => 'metal', 'eye_color' => 'red'],
			['name' => 'Bossk', 'height' => 190, 'mass' => 113, 'gender' => 'male', 'hair_color' => 'none', 'skin_color' => 'green', 'eye_color' => 'red'],
			['name' => 'Lando Calrissian', 'height' => 177, 'mass' => 79, 'gender' => 'male', 'hair_color' => 'black', 'skin_color' => 'dark', 'eye_color' => 'brown'],
			['name' => 'Lobot', 'height' => 175, 'mass' => 79, 'gender' => 'male', 'hair_color' => 'none', 'skin_color' => '#fff7ed', 'eye_color' => 'blue'],
			['name' => 'Ackbar', 'height' => 180, 'mass' => 83, 'gender' => 'male', 'hair_color' => 'none', 'skin_color' => 'brown mottle', 'eye_color' => 'orange'],
			['name' => 'Mon Mothma', 'height' => 150, 'mass' => 81, 'gender' => 'female', 'hair_color' => 'auburn', 'skin_color' => '#FFECD3', 'eye_color' => 'blue'],
			['name' => 'Arvel Crynyd', 'height' => null, 'mass' => 74, 'gender' => 'male', 'hair_color' => 'brown', 'skin_color' => '#FFECD3', 'eye_color' => 'brown'],
			['name' => 'Wicket Systri Warrick', 'height' => 88, 'mass' => 20, 'gender' => 'male', 'hair_color' => 'brown', 'skin_color' => 'brown', 'eye_color' => 'brown'],
			['name' => 'Nien Nunb', 'height' => 160, 'mass' => 68, 'gender' => 'male', 'hair_color' => 'none', 'skin_color' => 'grey', 'eye_color' => 'black'],
			['name' => 'Qui-Gon Jinn', 'height' => 193, 'mass' => 89, 'gender' => 'male', 'hair_color' => 'brown', 'skin_color' => '#FFECD3', 'eye_color' => 'blue'],
			['name' => 'Nute Gunray', 'height' => 191, 'mass' => 90, 'gender' => 'male', 'hair_color' => 'none', 'skin_color' => 'mottled green', 'eye_color' => 'red'],
			['name' => 'Finis Valorum', 'height' => 170, 'mass' => 82, 'gender' => 'male', 'hair_color' => 'yellow', 'skin_color' => '#FFECD3', 'eye_color' => 'blue'],
			['name' => 'Jar Jar Binks', 'height' => 196, 'mass' => 66, 'gender' => 'male', 'hair_color' => 'none', 'skin_color' => 'orange', 'eye_color' => 'orange'],
			['name' => 'Roos Tarpals', 'height' => 224, 'mass' => 82, 'gender' => 'male', 'hair_color' => 'none', 'skin_color' => 'grey', 'eye_color' => 'orange'],
			['name' => 'Rugor Nass', 'height' => 206, 'mass' => 95, 'gender' => 'male', 'hair_color' => 'none', 'skin_color' => 'green', 'eye_color' => 'orange'],
			['name' => 'Ric Olié', 'height' => 183, 'mass' => 84, 'gender' => 'male', 'hair_color' => 'brown', 'skin_color' => '#FFECD3', 'eye_color' => 'blue'],
			['name' => 'Watto', 'height' => 137, 'mass' => 56, 'gender' => 'male', 'hair_color' => 'black', 'skin_color' => 'blue, grey', 'eye_color' => 'yellow'],
			['name' => 'Sebulba', 'height' => 112, 'mass' => 40, 'gender' => 'male', 'hair_color' => 'none', 'skin_color' => 'grey, red', 'eye_color' => 'orange'],
			['name' => 'Quarsh Panaka', 'height' => 183, 'mass' => 71, 'gender' => 'male', 'hair_color' => 'black', 'skin_color' => 'dark', 'eye_color' => 'brown'],
		];

		// Liste de Planètes
		$arrayPlanets = [

			// Structure d'un élément
			[
				'name' => 'Alderaan', 
				'climate' => 'temperate', 
				'terrain' => 'grasslands, mountains', 
				'population' => 2000000000
			],

			// Les autres éléments
			['name' => 'Yavin IV', 'climate' => 'temperate, tropical', 'terrain' => 'jungle, rainforests', 'population' => 1000],
			['name' => 'Hoth', 'climate' => 'frozen', 'terrain' => 'tundra, ice caves, mountain ranges', 'population' => null],
			['name' => 'Dagobah', 'climate' => 'murky', 'terrain' => 'swamp, jungles', 'population' => null],
			['name' => 'Bespin', 'climate' => 'temperate', 'terrain' => 'gas giant', 'population' => 6000000],
			['name' => 'Endor', 'climate' => 'temperate', 'terrain' => 'forests, mountains, lakes', 'population' => 30000000],
			['name' => 'Naboo', 'climate' => 'temperate', 'terrain' => 'grassy hills, swamps, forests, mountains', 'population' => 4500000000],
			['name' => 'Coruscant', 'climate' => 'temperate', 'terrain' => 'cityscape, mountains', 'population' => 1000000000000],
			['name' => 'Kamino', 'climate' => 'temperate', 'terrain' => 'ocean', 'population' => 1000000000],
			['name' => 'Geonosis', 'climate' => 'temperate, arid', 'terrain' => 'rock, desert, mountain, barren', 'population' => 100000000000],
			['name' => 'Utapau', 'climate' => 'temperate, arid, windy', 'terrain' => 'scrublands, savanna, canyons, sinkholes', 'population' => 95000000],
			['name' => 'Mustafar', 'climate' => 'hot', 'terrain' => 'volcanoes, lava rivers, mountains, caves', 'population' => 20000],
			['name' => 'Kashyyyk', 'climate' => 'tropical', 'terrain' => 'jungle, forests, lakes, rivers', 'population' => 45000000],
			['name' => 'Polis Massa', 'climate' => 'artificial temperate ', 'terrain' => 'airless asteroid', 'population' => 1000000],
			['name' => 'Mygeeto', 'climate' => 'frigid', 'terrain' => 'glaciers, mountains, ice canyons', 'population' => 19000000],
			['name' => 'Felucia', 'climate' => 'hot, humid', 'terrain' => 'fungus forests', 'population' => 8500000],
			['name' => 'Cato Neimoidia', 'climate' => 'temperate, moist', 'terrain' => 'mountains, fields, forests, rock arches', 'population' => 10000000],
			['name' => 'Saleucami', 'climate' => 'hot', 'terrain' => 'caves, desert, mountains, volcanoes', 'population' => 1400000000],
			['name' => 'Stewjon', 'climate' => 'temperate', 'terrain' => 'grass', 'population' => null],
			['name' => 'Eriadu', 'climate' => 'polluted', 'terrain' => 'cityscape', 'population' => 22000000000],
			['name' => 'Corellia', 'climate' => 'temperate', 'terrain' => 'plains, urban, hills, forests', 'population' => 3000000000],
			['name' => 'Rodia', 'climate' => 'hot', 'terrain' => 'jungles, oceans, urban, swamps', 'population' => 1300000000],
			['name' => 'Nal Hutta', 'climate' => 'temperate', 'terrain' => 'urban, oceans, swamps, bogs', 'population' => 7000000000],
			['name' => 'Dantooine', 'climate' => 'temperate', 'terrain' => 'oceans, savannas, mountains, grasslands', 'population' => 1000],
			['name' => 'Bestine IV', 'climate' => 'temperate', 'terrain' => 'rocky islands, oceans', 'population' => 62000000],
			['name' => 'Ord Mantell', 'climate' => 'temperate', 'terrain' => 'plains, seas, mesas', 'population' => 4000000000],
			['name' => 'Trandosha', 'climate' => 'arid', 'terrain' => 'mountains, seas, grasslands, deserts', 'population' => 42000000],
			['name' => 'Socorro', 'climate' => 'arid', 'terrain' => 'deserts, mountains', 'population' => 300000000],
			['name' => 'Mon Cala', 'climate' => 'temperate', 'terrain' => 'oceans, reefs, islands', 'population' => 27000000000],
			['name' => 'Chandrila', 'climate' => 'temperate', 'terrain' => 'plains, forests', 'population' => 1200000000],
			['name' => 'Sullust', 'climate' => 'superheated', 'terrain' => 'mountains, volcanoes, rocky deserts', 'population' => 18500000000],
			['name' => 'Toydaria', 'climate' => 'temperate', 'terrain' => 'swamps, lakes', 'population' => 11000000],
			['name' => 'Malastare', 'climate' => 'arid, temperate, tropical', 'terrain' => 'swamps, deserts, jungles, mountains', 'population' => 2000000000],
			['name' => 'Dathomir', 'climate' => 'temperate', 'terrain' => 'forests, deserts, savannas', 'population' => 5200],
			['name' => 'Ryloth', 'climate' => 'temperate, arid, subartic', 'terrain' => 'mountains, valleys, deserts, tundra', 'population' => 1500000000],
			['name' => 'Aleen Minor', 'climate' => 'unknown', 'terrain' => 'unknown', 'population' => null],
			['name' => 'Vulpter', 'climate' => 'temperate, artic', 'terrain' => 'urban, barren', 'population' => 421000000],
			['name' => 'Troiken', 'climate' => 'unknown', 'terrain' => 'desert, tundra, rainforests, mountains', 'population' => null],
			['name' => 'Tund', 'climate' => 'unknown', 'terrain' => 'barren, ash', 'population' => 0],
		];